#!/usr/bin/sh

docker stop spm-ui-upgrade-helper
docker rm spm-ui-upgrade-helper

INPUT_FOLDER=/tmp/ui-upgrade-helper/input
OUTPUT_FOLDER=/tmp/ui-upgrade-helper/output

docker run -d -p 3000:3000 -p 4000-4004:4000-4004 -v $INPUT_FOLDER:/home/workspace/input -v $OUTPUT_FOLDER:/home/workspace/output --name spm-ui-upgrade-helper docker.io/ibmcom/spm-ui-upgrade-helper:latest
